---
dependency:
  name: galaxy
driver:
  name: docker
platforms:    
  - name: appium
    options:
      ansible_python_interpreter: /usr/bin/python3
    image: ubuntu:latest
    log: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
